server:
  port: 8089

spring:
  application:
    name: service-provider
  datasource:
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/my1803?useUnicode=true&characterEncoding=utf-8
    username: root

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/



