eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8092
spring:
  application:
    name: front-comsumer
    thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html


ribbon:
  eureka:
    enabled: true
redis:
  host: 127.0.0.1
  maxActive: 600
  maxIdle: 300
  maxWait: 1000
  pass: ''
  port: 6379
  testOnBorrow: true
#feign:
#  hystrix:
#    enabled: true

#  httpclient:
#    enabled: true


