eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8082
  max-http-header-size: 4048576

spring:
  application:
    name: service-comsumer
    thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html



ribbon:
  eureka:
    enable: true




#feign:
#  hystrix:
#    enabled: true

#  httpclient:
#    enabled: true

