eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8082
spring:
  application:
    name: service-comsumer
    thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html

#feign:
#  hystrix:
#    enabled: true

#  httpclient:
#    enabled: true

